name: Nuestro Primer PipeLine
on:
  pull_request: 
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Analizamos el proyecto
    - name: Ejecutamos un comando
      run: echo Esta ejecutando el PipeLine
    - name: Ejecutamos varias lineas
      run: |
        echo Varias lineas
        ls -la
